version: 0.0
os: linux
files:
  - source: /
  destination: /var/www/html/best-partner

permissions:
  - object: /var/www/html/best-partner
    owner: ec2-user
    group: ec2-user


hooks:
  AfterInstall:
    - location: ./scripts/after_install.sh
    timeout: 60
    tunas: ec2-user


    
    